image: node:12.10.0-stretch-slim

pipelines:
  tags:
    "*.*.*": # Pipeline for Semantic Version Tags
      - step: # Step 1 - NPM Install and Build
          name: "NPM Install and Build"
          size: 2x
          caches:
            - node
          script:
            - mv .npmrc_config .npmrc
            - rm -rf ./node_modules
            - npm ci
            - npm run build:ci
          artifacts:
            - "build/**"
      - step: # Step 2 - Build a Docker Image and Push
          name: "Build and Push Docker Image"
          services:
            - docker
          caches: #TODO: Consider disabling this as our cache uploads are large and take forever!
            - docker
          script:
            - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - docker build -t $DOCKER_IMAGE_NAME .
            - docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:latest # TODO: Remove Latest Tag as this should be handled on a Commit to Master (latest doesn't follow a tag)
            - docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:$BITBUCKET_TAG
            - docker push $DOCKER_IMAGE_NAME:latest # TODO: Remove Latest Push as this should be handled on a Commit to Master (latest doesn't follow a tag)
            - docker push $DOCKER_IMAGE_NAME:$BITBUCKET_TAG
            # TODO: We may need to run a Docker Prune before we finish to clean up images /layers we don't want to cache?
      - step: # Step 3 - Create Octopus Release
          name: "Create Octopus Release"
          image: octopusdeploy/octo:7.3.2-alpine
          script:
            - octo create-release --version $BITBUCKET_TAG --defaultPackageVersion $BITBUCKET_TAG --project "$OCTOPUS_PROJECT_NAME" --server $OCTOPUS_SERVER --apiKey $OCTOPUS_APIKEY
      - step: # Step 4 - Push Build Information to Bugsnag
          name: "Bugsnag Build Information"
          script:
            - pipe: bugsnag-integrations/bugsnag-build-report:0.2.2
              variables:
                API_KEY: $BUGSNAG_APIKEY
                APP_VERSION: $BITBUCKET_TAG
